# Generated by Django 3.1.2 on 2020-10-17 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('surname', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('academic_title', models.CharField(choices=[('dr', 'dr'), ('dr inż.', 'dr inż.'), ('dr hab.', 'dr hab.'), ('mgr inż.', 'mgr inż.')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(blank=True, choices=[('Monday', 0), ('Tuesday', 1), ('Wednesday', 2), ('Thursday', 3), ('Friday', 4), ('Saturday', 5), ('Sunday', 6)], null=True)),
                ('weeks', models.CharField(choices=[('1/3', '1/3'), ('2/4', '2/4')], max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('start_time', models.TimeField()),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('group', models.IntegerField(blank=True, null=True)),
                ('laboratories', models.IntegerField(blank=True, null=True)),
                ('hall', models.IntegerField(blank=True, null=True)),
                ('building', models.CharField(max_length=100, null=True)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduleServer.lecturer')),
            ],
        ),
        migrations.CreateModel(
            name='FieldOfStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(blank=True, choices=[('1year 1semester', 1), ('1year 2semester', 2), ('2year 1semester', 3), ('2year 2semester', 4), ('3year 1semester', 5), ('3year 2semester', 6), ('4year 1semester', 7)], null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('lectures', models.ManyToManyField(to='scheduleServer.Lecturer')),
            ],
        ),
    ]
