# Generated by Django 3.1.2 on 2020-10-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleServer', '0003_auto_20201017_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldofstudy',
            name='lectures',
            field=models.ManyToManyField(blank=True, to='scheduleServer.Lecture'),
        ),
    ]
