# Generated by Django 3.1.2 on 2020-10-17 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleServer', '0006_auto_20201017_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='teacher',
            new_name='lecturer',
        ),
    ]
