# Generated by Django 3.1.2 on 2020-10-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleServer', '0007_auto_20201017_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldofstudy',
            name='lectures',
        ),
        migrations.AddField(
            model_name='lecture',
            name='fielf_of_study',
            field=models.ManyToManyField(null=True, to='scheduleServer.FieldOfStudy'),
        ),
    ]
