# Generated by Django 3.1.2 on 2020-10-20 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleServer', '0008_auto_20201017_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall', models.IntegerField(blank=True, null=True)),
                ('building', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='hall',
        ),
        migrations.AlterField(
            model_name='lecture',
            name='fielf_of_study',
            field=models.ManyToManyField(to='scheduleServer.FieldOfStudy'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduleServer.building'),
        ),
    ]
