# Generated by Django 3.1.2 on 2020-10-20 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleServer', '0009_auto_20201020_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldofstudy',
            name='semester',
            field=models.IntegerField(blank=True, choices=[(1, '1 year 1 semester'), (2, '1 year 2 semester'), (3, '2 year 1 semester'), (4, '2 year 2 semester'), (5, '3 year 1 semester'), (6, '3 year 2 semester'), (7, '4 year 1 semester')], null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduleServer.building'),
        ),
    ]
