# Generated by Django 3.1.2 on 2020-10-31 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleServer', '0010_auto_20201020_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldofstudy',
            name='year',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
