# Generated by Django 3.1.2 on 2020-10-31 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleServer', '0011_auto_20201031_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='duration',
        ),
    ]
