# Generated by Django 3.1.2 on 2020-11-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleServer', '0012_remove_lecture_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='fieldofstudy',
            name='specjalization',
            field=models.ManyToManyField(to='scheduleServer.Specialization'),
        ),
    ]
