# Generated by Django 3.1.2 on 2020-11-01 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleServer', '0014_auto_20201101_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialization',
            old_name='shortName',
            new_name='short_name',
        ),
    ]
