# Generated by Django 3.1.2 on 2020-11-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleServer', '0015_auto_20201101_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldofstudy',
            old_name='specjalization',
            new_name='specialization',
        ),
        migrations.AlterField(
            model_name='specialization',
            name='short_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
