# Generated by Django 3.1.2 on 2020-11-12 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleServer', '0020_auto_20201112_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduleServer.specialization'),
        ),
    ]
