# Generated by Django 3.1.2 on 2020-11-13 14:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleServer', '0021_auto_20201113_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weeks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('dates', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, size=None)),
            ],
        ),
    ]
