# Generated by Django 3.1.2 on 2020-11-13 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleServer', '0022_weeks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Weeks',
        ),
    ]
